# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: En Marche ! Martinique
email: e.marche972@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pour ceux qui sont convaincus que le pays est bloqué, qui ont le goût du travail, du progrès,
  du risque, qui vivent pour la liberté, l'égalité, et l'Europe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: enmarche972
github_username:  lobos-tudio
facebook_app_id: enmarche972
sass:
  sass_dir: _scss
# paginate: 12
pagination:
  enabled: true
  per_page: 12
  permalink: '/page/:num/'
  title: 'Articles - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
markdown: kramdown
github: [metadata]

languages: ["fr", "en", "ht"]
default_lang: "fr"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

exclude:
  - Gemfile
  - Gemfile.lock
